### ISSUE TITLE
Looking forward to the full version of this

### ISSUE THREAD

**Issue by Kishan-Athrey** [AnyiRao/SceneSeg#1]
This is a very interesting idea, looking forward to the full version of the code

**Comment by anyirao** [comment]
Thanks so much for your interest! The plan is to release the easy-to-use toolkit and some full-functional preprocessing tools in July. A webpage will also be set up with tutorials' guidance. We are working hard on it recently and it is almost done. :)

**Comment by anyirao** [comment]
Check it here. Please check out here https://github.com/movienet/movienet-tools

Thanks all for so many interests. 😄
