### ISSUE TITLE
The dimension of cast_feature using movienet-tool is defferent from yours in cast_feat.pkl

### ISSUE THREAD

**Issue by lmaors** [AnyiRao/SceneSeg#12]
hello，
when i use movie-tool tu reduce cast_feat,i get the dimension of feature is (256,)
![Screenshot from 2020-10-30 16-40-59](https://user-images.githubusercontent.com/61704530/97678471-cffd4800-1ace-11eb-8a36-7f10891f7c1c.png)
I check  your cast feature in cast_feature.pkl, the dimension is (512,):
![Screenshot from 2020-10-30 16-44-26](https://user-images.githubusercontent.com/61704530/97678731-426e2800-1acf-11eb-868e-caed7bc2ee9f.png)
What can i do to get the dimension or cast feature is (512,)?

**Comment by anyirao** [comment]
Hello Dear @lmaors ,

What you concern is right. Please check #5 for more details.

Best,
