### ISSUE TITLE
Clarification on how data is obtained

### ISSUE THREAD

**Issue by humzaiqbal** [AnyiRao/SceneSeg#16]
Hi, thanks a lot for the great repo! One question, I notice that in `all.py` you have the following line,

https://github.com/AnyiRao/SceneSeg/blob/94c3a9e0e811271d481576d4918e5cc2f018112c/lgss/src/data/all.py#L107-L110

does that mean you only train / run inference on shots that can be fully covered by the window length divided by 2? (Ie the 1st and 2nd shot of a movie would not be trained on at all with a window size of 4 and half window size 2). Also if thats the case then what about the shots at the very end (the last and second to last shot with the same window sizes as above) Trying to understand how the data is fed into the model, thanks!

**Comment by anyirao** [comment]
Yes @humzaiqbal, what you understand is right. Since we adopt sliding windows in our model, the very start and end cannot be handled. To handle them, it is suggested to train another model with a small sliding window to specially process these cases.
