### ISSUE TITLE
No checkpoint found at '../run/image50/model_best.pth.tar'

### ISSUE THREAD

**Issue by PatriciaBota** [AnyiRao/SceneSeg#19]
When I run python run.py config/demo.py I am getting the following error:

Traceback (most recent call last):
  File "run.py", line 210, in <module>
    main()
  File "run.py", line 186, in main
    osp.join(cfg.logger.logs_dir, 'model_best.pth.tar'))
  File "/Users/X/Downloads/SceneSeg-master-2/lgss/utilis/torch_utilis.py", line 35, in load_checkpoint
    raise ValueError("=> No checkpoint found at '{}'".format(fpath))
ValueError: => No checkpoint found at '../run/image50/model_best.pth.tar'

If I have my own video is the the code atm able to return the scenes frame indexes (when each scene starts)? What part should I run? the demo?

Thank you for making this open source and all the help.

**Comment by yrf1** [comment]
You can download the model checkpoint from the Google Drive link installed the install readme
