### ISSUE TITLE
'image18_demo' model missing

### ISSUE THREAD

**Issue by albertaparicio** [AnyiRao/SceneSeg#2]
I tried running the demo, following the steps in GETTING_STARTED.md and when I run `lgss $ python run.py config/demo.py` I get this error:

`ValueError: => No checkpoint found at '../run/image18_demo/model_best.pth.tar'`

I checked the `run` directory in Google Drive and there is no `image18_demo` directory.

Can I run the demo with the `image50` model? Could you provide the `image18_demo` model please?

Thank you, this project looks promising

**Comment by anyirao** [comment]
Thanks for your pointing out. We have updated the config file. `image50` model is ready to use. If you still want to use `image18` i.e. resnet 18 as the backbone, please provide an email address here and I will send it to you.
