### ISSUE TITLE
how can I segment my video with place、audio features into scenes

### ISSUE THREAD

**Issue by chenping5121** [AnyiRao/SceneSeg#4]
could you integrate end-to-end testing code for me to get scenes videos？I'm reading these codes with but I don't know what the args mean?

**Comment by anyirao** [comment]
You may try the demo code which takes images as inputs. As for the thing you said, since it requires incorporating feature extractor (we are currently working on this to make it easy to use) into the end-to-end fashion, we may develop it in the future.
