### ISSUE TITLE
issue of transfer learning: train on the given labeled data and evaluated the model on the other set

### ISSUE THREAD

**Issue by jdongca2003** [AnyiRao/SceneSeg#6]
Hi, Anyi
     I trained the model based on labeled data and place_feat.zip. Here I assume that features are extracted for shots based on pretrained pytorch resnet50.  On your provided labelled data, AUC on the testing was about 0.75. But when I tested it on BBC earth planet dataset using pre/place/extract_feat.py,  AUC on the bbc dataset is only 0.55.   Do you have clue?

Thanks

Jianxiong

**Comment by jdongca2003** [comment]
sorry. it is related to my code bug.

**Comment by Bonnie970** [comment]
Hi @jdongca2003, I'm also trying to test on BBC dataset, got similar low AP scores, still debugging. BBC dataset has scene ground truth labeled by 5 annotators, how did you generate the final ground truth from these 5 sets? Very appreciated your help.
