### ISSUE TITLE
pytube issue

### ISSUE THREAD

**Issue by miaoqiz** [AnyiRao/SceneSeg#8]
Hi,

There seem to be two issues related to the usage of "pytube" in this project:

1. It looks like "pytube" should be installed with "pip3 install pytube3";
2. When running "demodownload.py" inside "pre" directory, there seem to be an error related to "key" (see below)

formats = json.loads(stream_data["player_response"])["streamingData"][
KeyError: 'streamingData'

Please kindly advise.

Thanks so much and have a good day!

**Comment by anyirao** [comment]
Hi miaoqiz,

Thanks for your interest in this project. This is because the link is invalid now, as the stuff on YouTube changes quite often. 

I upload a new one, and you can also change to your own as you like.

Thanks,

**Comment by miaoqiz** [comment]
Hi,

Thanks so much for the quick reply!

I think changing the URL fixed the key issue; however, there may be a need to remove certain character(s) (e.g., '-') from the title so you can rename the file with "shutil.move (...)".

Have a good day!
